//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.1
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FISCA.DSAUtil {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FISCA.DSAUtil.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 http://dsns1.ischool.com.tw/dsns/dsns
        ///http://dsns2.ischool.com.tw/dsns/dsns
        ///http://124.219.8.11/dsns/dsns
        ///http://203.72.205.3/dsns/dsns
        ///http://dsns-gae.appspot.com/dsns
        ///http://dsns.blazer.org.tw/commonserver/dsnameservice/accesspoint.dsa
        ///http://203.72.205.3/commonserver/dsnameservice/accesspoint.dsa
        ///http://124.219.8.3/commonserver/dsnameservice/accesspoint.dsa 的當地語系化字串。
        /// </summary>
        internal static string DSNSServerList {
            get {
                return ResourceManager.GetString("DSNSServerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///	elementFormDefault=&quot;qualified&quot;&gt;
        ///
        ///	&lt;xs:element name=&quot;Envelope&quot;&gt;
        ///		&lt;xs:complexType&gt;
        ///			&lt;xs:sequence&gt;
        ///				&lt;xs:element name=&quot;Header&quot; type=&quot;header&quot; /&gt;
        ///				&lt;xs:element name=&quot;Body&quot; type=&quot;body&quot;/&gt;
        ///			&lt;/xs:sequence&gt;
        ///		&lt;/xs:complexType&gt;
        ///	&lt;/xs:element&gt;
        ///
        ///	&lt;xs:complexType name=&quot;header&quot;&gt;
        ///		&lt;xs:sequence&gt;
        ///			&lt;xs:any minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot; processContents=&quot;skip&quot;/&gt;
        ///		&lt;/xs:sequence&gt;
        ///	&lt;/xs:complexType&gt;
        ///	 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string EnvelopeSchema {
            get {
                return ResourceManager.GetString("EnvelopeSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///	elementFormDefault=&quot;qualified&quot;&gt;
        ///
        ///	&lt;xs:element name=&quot;Envelope&quot;&gt;
        ///		&lt;xs:complexType&gt;
        ///			&lt;xs:sequence&gt;
        ///				&lt;xs:element name=&quot;Header&quot; type=&quot;EnvelopeHeader&quot; /&gt;
        ///				&lt;xs:element name=&quot;Body&quot; type=&quot;EnvelopeBody&quot;/&gt;
        ///			&lt;/xs:sequence&gt;
        ///		&lt;/xs:complexType&gt;
        ///	&lt;/xs:element&gt;
        ///
        ///	&lt;xs:complexType name=&quot;EnvelopeHeader&quot;&gt;
        ///		&lt;xs:sequence&gt;
        ///			&lt;xs:element name=&quot;TargetContract&quot; type=&quot;xs:string&quot; minOccurs=&quot;0&quot;/&gt;
        ///			&lt;xs:element na [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string RequestSchema {
            get {
                return ResourceManager.GetString("RequestSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///	elementFormDefault=&quot;qualified&quot;&gt;
        ///
        ///	&lt;xs:element name=&quot;Request&quot;&gt;
        ///		&lt;xs:complexType&gt;
        ///			&lt;xs:sequence&gt;
        ///				&lt;!--不要把maxOccurs設成1，因為舊的程式也許會有TextNode，這樣會造成錯誤。--&gt;
        ///				&lt;xs:any minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot; processContents=&quot;skip&quot;/&gt;
        ///			&lt;/xs:sequence&gt;
        ///			&lt;xs:attribute use=&quot;required&quot; name=&quot;ServiceName&quot; type=&quot;xs:string&quot;/&gt;
        ///			&lt;xs:attribute use=&quot;required&quot; name=&quot;UserID&quot; type=&quot;xs:string&quot;/&gt;
        ///			&lt;xs:attribute use=&quot;requ [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string RequestSchemaOld {
            get {
                return ResourceManager.GetString("RequestSchemaOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///	elementFormDefault=&quot;qualified&quot;&gt;
        ///
        ///	&lt;xs:element name=&quot;Envelope&quot;&gt;
        ///		&lt;xs:complexType&gt;
        ///			&lt;xs:sequence&gt;
        ///				&lt;xs:element name=&quot;Header&quot; type=&quot;EnvelopeHeader&quot; /&gt;
        ///				&lt;xs:element name=&quot;Body&quot; type=&quot;EnvelopeBody&quot;/&gt;
        ///			&lt;/xs:sequence&gt;
        ///		&lt;/xs:complexType&gt;
        ///	&lt;/xs:element&gt;
        ///
        ///	&lt;xs:complexType name=&quot;EnvelopeHeader&quot;&gt;
        ///		&lt;xs:sequence&gt;
        ///			&lt;xs:element name=&quot;Status&quot; minOccurs=&quot;1&quot; maxOccurs=&quot;1&quot;&gt;
        ///				&lt;xs:complexType&gt;
        ///					&lt;x [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string ResponseSchema {
            get {
                return ResourceManager.GetString("ResponseSchema", resourceCulture);
            }
        }
    }
}
