//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQL() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Manager.SQL", typeof(SQL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 select pg_database.oid,datname,description 
        ///from pg_database left join pg_shdescription on pg_database.oid=pg_shdescription.objoid 的當地語系化字串。
        /// </summary>
        internal static string ListDatabase {
            get {
                return ResourceManager.GetString("ListDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CREATE DATABASE &quot;{0}&quot; WITH OWNER = postgres Template &quot;{1}&quot;; 的當地語系化字串。
        /// </summary>
        internal static string NewDatabase {
            get {
                return ResourceManager.GetString("NewDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 select id,identity,log_time,dsa_application_name,dsa_contract_name,dsa_service_name,process_time,(exception!=&apos;&apos;) as occure_exception
        ///from log 
        ///where date_trunc(&apos;{0}&apos;,log_time)=&apos;{1}&apos;  {2}
        ///order by log_time 的當地語系化字串。
        /// </summary>
        internal static string QueryRspTimeDetail {
            get {
                return ResourceManager.GetString("QueryRspTimeDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 select date_trunc(&apos;{0}&apos;,log_time) as group_time,count(*) as pcount,avg(process_time) as avg_rsp_time,max(process_time) as max_rsp_time,min(process_time) as min_rsp_time,sum(process_time) as total_rsp_time
        ///from log
        ///{1}
        ///group by group_time
        ///order by {2}
        ///limit {3} 的當地語系化字串。
        /// </summary>
        internal static string ServerRspTime {
            get {
                return ResourceManager.GetString("ServerRspTime", resourceCulture);
            }
        }
    }
}
